


export const getProduct = ()=>{
    try{

    }
    catch(error)
    {
        console.log('Error: ',error.message);
    }
}